### PR TITLE
depricating role mode option durning provisioning phase

### PR DESCRIPTION
**Pull request by jearly**
Removing for_autoscaling option from attributes and helpers as role mode is being deprecated in the next release.

### CODE REVIEW

**Comment by joelvanvelden** [comment]
@jearly Can you please provide more detail on why this is deprecated? 
My client relies heavily on this autoscaling support (which has now broken) and we need to understand if this is something we can patch around by restoring this "--inst-type role" functionality, or if we need to be looking to move to a different service provider.

**Comment by ryanholland** [comment]
@joelvanvelden Apologies we should have been more clear describing this change.  We are not dropping support for autoscaling but rather making enhancements that will allow agents installed using the host mode to handle both autoscaling and non-autoscaling instances thus removing the need to designate autoscaling instances as part of a role.  Also the role mode has not yet been removed from the agent so to answer your question, yes you can continue to use "--inst-type role" for the time being but it would be recommended to start moving over to host mode installations as later this year that will be removed.

**Comment by joelvanvelden** [comment]
@ryanholland 
Thank you for the update.
Do you have any documentation about how autoscaling with inst-type host works? This must be new functionality? Is is released yet, or future?

**Comment by ryanholland** [comment]
@joelvanvelden Sorry about the delay in responding - yes it is new functionality, it has been in beta for a few months and will be released generally in the coming weeks.  There will be updated documentation and notifications going out to all customers shortly.  
Thanks
Ryan

**Pull request merged**
